---
- name: Check Memory Information
  hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: Show Total Memory
      debug:
        msg: "Total Memory: {{ansible_memtotal_mb}} MB"

    - name: Show Free Memory
      debug:
        msg: "Free Memory: {{ansible_memfree_mb}} MB"

